/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.20.1"
    },
    date = "2018-02-20T12:40:27.692Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventory extends SchemaImpl {

    private static final long serialVersionUID = 73684262;

    /**
     * The reference instance of <code>inventory</code>
     */
    public static final Inventory INVENTORY = new Inventory();

    /**
     * The table <code>inventory.product</code>.
     */
    public final Product PRODUCT = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product.PRODUCT;

    /**
     * No further instances allowed
     */
    private Inventory() {
        super("inventory", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Product.PRODUCT);
    }
}
