/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.StoreRoom;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.26.1"
    },
    date = "2018-02-26T09:43:39.080Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventory extends SchemaImpl {

    private static final long serialVersionUID = -1639836213;

    /**
     * The reference instance of <code>inventory</code>
     */
    public static final Inventory INVENTORY = new Inventory();

    /**
     * The table <code>inventory.product</code>.
     */
    public final Product PRODUCT = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product.PRODUCT;

    /**
     * The table <code>inventory.product_stock</code>.
     */
    public final ProductStock PRODUCT_STOCK = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock.PRODUCT_STOCK;

    /**
     * The table <code>inventory.store_room</code>.
     */
    public final StoreRoom STORE_ROOM = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.StoreRoom.STORE_ROOM;

    /**
     * No further instances allowed
     */
    private Inventory() {
        super("inventory", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Product.PRODUCT,
            ProductStock.PRODUCT_STOCK,
            StoreRoom.STORE_ROOM);
    }
}
