/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.StoreRoom;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records.ProductRecord;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records.ProductStockRecord;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records.StoreRoomRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>inventory</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.27.0"
    },
    date = "2018-02-27T09:22:15.375Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductRecord> PK_PRODUCT = UniqueKeys0.PK_PRODUCT;
    public static final UniqueKey<ProductStockRecord> PK_PRODUCT_STOCK = UniqueKeys0.PK_PRODUCT_STOCK;
    public static final UniqueKey<StoreRoomRecord> PK_STORE_ROOM = UniqueKeys0.PK_STORE_ROOM;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ProductRecord> PK_PRODUCT = createUniqueKey(Product.PRODUCT, "pk_product", Product.PRODUCT.P_ID);
        public static final UniqueKey<ProductStockRecord> PK_PRODUCT_STOCK = createUniqueKey(ProductStock.PRODUCT_STOCK, "pk_product_stock", ProductStock.PRODUCT_STOCK.PS_ID);
        public static final UniqueKey<StoreRoomRecord> PK_STORE_ROOM = createUniqueKey(StoreRoom.STORE_ROOM, "pk_store_room", StoreRoom.STORE_ROOM.SR_ID);
    }
}
