/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in inventory
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.20.1"
    },
    date = "2018-02-20T12:40:27.692Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inventory.product</code>.
     */
    public static final Product PRODUCT = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product.PRODUCT;
}
