/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.StoreRoom;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in inventory
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.22.1"
    },
    date = "2018-02-22T16:24:19.217Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inventory.product</code>.
     */
    public static final Product PRODUCT = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product.PRODUCT;

    /**
     * The table <code>inventory.product_stock</code>.
     */
    public static final ProductStock PRODUCT_STOCK = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock.PRODUCT_STOCK;

    /**
     * The table <code>inventory.store_room</code>.
     */
    public static final StoreRoom STORE_ROOM = cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.StoreRoom.STORE_ROOM;
}
