/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.Inventory;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.Keys;
import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records.ProductStockRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.27.0"
    },
    date = "2018-02-27T09:22:15.375Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductStock extends TableImpl<ProductStockRecord> {

    private static final long serialVersionUID = 663732995;

    /**
     * The reference instance of <code>inventory.product_stock</code>
     */
    public static final ProductStock PRODUCT_STOCK = new ProductStock();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductStockRecord> getRecordType() {
        return ProductStockRecord.class;
    }

    /**
     * The column <code>inventory.product_stock.ps_id</code>.
     */
    public final TableField<ProductStockRecord, String> PS_ID = createField("ps_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>inventory.product_stock.ps_stock</code>.
     */
    public final TableField<ProductStockRecord, Integer> PS_STOCK = createField("ps_stock", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>inventory.product_stock.ps_storeroom_id</code>.
     */
    public final TableField<ProductStockRecord, String> PS_STOREROOM_ID = createField("ps_storeroom_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>inventory.product_stock.ps_product_id</code>.
     */
    public final TableField<ProductStockRecord, String> PS_PRODUCT_ID = createField("ps_product_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>inventory.product_stock</code> table reference
     */
    public ProductStock() {
        this("product_stock", null);
    }

    /**
     * Create an aliased <code>inventory.product_stock</code> table reference
     */
    public ProductStock(String alias) {
        this(alias, PRODUCT_STOCK);
    }

    private ProductStock(String alias, Table<ProductStockRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductStock(String alias, Table<ProductStockRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inventory.INVENTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductStockRecord> getPrimaryKey() {
        return Keys.PK_PRODUCT_STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductStockRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductStockRecord>>asList(Keys.PK_PRODUCT_STOCK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStock as(String alias) {
        return new ProductStock(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductStock rename(String name) {
        return new ProductStock(name, null);
    }
}
