/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.Product;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.20.1"
    },
    date = "2018-02-20T12:40:27.692Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 677225461;

    /**
     * Setter for <code>inventory.product.p_id</code>.
     */
    public void setPId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>inventory.product.p_id</code>.
     */
    public String getPId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>inventory.product.p_name</code>.
     */
    public void setPName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inventory.product.p_name</code>.
     */
    public String getPName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Product.PRODUCT.P_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.P_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(String value) {
        setPId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setPName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(String pId, String pName) {
        super(Product.PRODUCT);

        set(0, pId);
        set(1, pName);
    }
}
