/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.records;


import cabanas.garcia.ismael.inventory.infrastructure.repository.jooq.autogen.tables.ProductStock;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:inventory_2018.02.27.0"
    },
    date = "2018-02-27T09:22:15.375Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductStockRecord extends UpdatableRecordImpl<ProductStockRecord> implements Record4<String, Integer, String, String> {

    private static final long serialVersionUID = 1949872679;

    /**
     * Setter for <code>inventory.product_stock.ps_id</code>.
     */
    public void setPsId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>inventory.product_stock.ps_id</code>.
     */
    public String getPsId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>inventory.product_stock.ps_stock</code>.
     */
    public void setPsStock(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inventory.product_stock.ps_stock</code>.
     */
    public Integer getPsStock() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inventory.product_stock.ps_storeroom_id</code>.
     */
    public void setPsStoreroomId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>inventory.product_stock.ps_storeroom_id</code>.
     */
    public String getPsStoreroomId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>inventory.product_stock.ps_product_id</code>.
     */
    public void setPsProductId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>inventory.product_stock.ps_product_id</code>.
     */
    public String getPsProductId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProductStock.PRODUCT_STOCK.PS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProductStock.PRODUCT_STOCK.PS_STOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProductStock.PRODUCT_STOCK.PS_STOREROOM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProductStock.PRODUCT_STOCK.PS_PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPsStock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPsStoreroomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPsProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStockRecord value1(String value) {
        setPsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStockRecord value2(Integer value) {
        setPsStock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStockRecord value3(String value) {
        setPsStoreroomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStockRecord value4(String value) {
        setPsProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductStockRecord values(String value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductStockRecord
     */
    public ProductStockRecord() {
        super(ProductStock.PRODUCT_STOCK);
    }

    /**
     * Create a detached, initialised ProductStockRecord
     */
    public ProductStockRecord(String psId, Integer psStock, String psStoreroomId, String psProductId) {
        super(ProductStock.PRODUCT_STOCK);

        set(0, psId);
        set(1, psStock);
        set(2, psStoreroomId);
        set(3, psProductId);
    }
}
